modLoader = "javafml"
loaderVersion = "[36,)"
issueTrackerURL = "https://github.com/${project.repoUser}/${project.repoName}/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/edit-sign"
logoFile="logo.png"
# credits=""
authors = "RakSrinaNa"
license = "GPL-3.0"

[[mods]] #mandatory
modId="${project.modId}"
version="${project.version}"
displayName = "${project.modName}"
updateJSONURL = "https://raw.githubusercontent.com/${project.repoUser}/${project.repoName}/${project.minecraft_version}/update.json"
description = '''Allow you to edit signs without breaking them.'''

[[dependencies.editsign]]
modId = "forge"
mandatory = true
versionRange = "[36.0.0,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.editsign]]
modId = "minecraft"
mandatory = true
versionRange = "[${project.minecraft_version}]"
ordering = "NONE"
side = "BOTH"
[[dependencies.editsign]]
modId = "cloth-config"
mandatory = false
ordering = "NONE"
side = "CLIENT"
