version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - RakSrinaNa
  - package-ecosystem: gradle
    directory: "/forge"
    schedule:
      interval: "daily"
    reviewers:
      - RakSrinaNa
  - package-ecosystem: gradle
    directory: "/fabric"
    schedule:
      interval: "daily"
    reviewers:
      - RakSrinaNa
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - RakSrinaNa
