modLoader="javafml"
loaderVersion="[34,)"
issueTrackerURL="https://github.com/${project.repoUser}/${project.repoName}/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/edit-sign"
logoFile="logo.png"
# credits=""
authors="RakSrinaNa"
license = "GPL-3.0"

[[mods]] #mandatory
	modId="${project.mod_id}"
	version="${project.version}"
    displayName="${project.modName}"
	updateJSONURL="https://raw.githubusercontent.com/${project.repoUser}/${project.repoName}/${project.repoBranch}/update.json"
	description='''Allow you to edit signs without breaking them.'''

[[dependencies.edit_sign]]
    modId="forge"
    mandatory=true
    versionRange="[34.0.0,)"
    ordering="NONE"
	side="BOTH"
[[dependencies.edit_sign]]
    modId="minecraft"
    mandatory=true
    versionRange="[${project.minecraft_version}]"
    ordering="NONE"
    side="BOTH"
