modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/RakSrinaNa/EditSign/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/edit-sign"
logoFile="logo.png"
# credits=""
authors="RakSrinaNa"

[[mods]] #mandatory
	modId="edit_sign"
	version="${file.jarVersion}"
	displayName="Edit Sign"
	updateJSONURL="https://raw.githubusercontent.com/RakSrinaNa/EditSign/1.15.2/update.json"
	description='''Allow you to edit signs without breaking them.'''

[[dependencies.edit_sign]]
    modId="forge"
    mandatory=true
    versionRange="[31.0.0,)"
    ordering="NONE"
	side="BOTH"
[[dependencies.edit_sign]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
