[versions]
modmenu-version = "2.0.2"
cloth-config-fabric-version = "5.0.34"
cloth-config-forge-version = "4.11.26"
lombok-version = "1.18.20"
minecraft-version = "1.17.1"
fabric-loader-version = "0.11.6"
fabric-api-version = "0.37.1+1.17"
forge-version = "1.17.1-37.0.17"

[libraries]
modmenu = { group = "com.terraformersmc", name = "modmenu", version.ref = "modmenu-version" }
clothConfigFabric = { group = "me.shedaniel.cloth", name = "cloth-config-fabric", version.ref = "cloth-config-fabric-version" }
clothConfigForge = { group = "me.shedaniel.cloth", name = "cloth-config-forge", version.ref = "cloth-config-forge-version" }
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok-version" }
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft-version" }
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader-version" }
fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric-api-version" }
forge = { group = "net.minecraftforge", name = "forge", version.ref = "forge-version" }

[bundles]
fabric = ["fabric-loader", "fabric-api"]